# Generated by Django 2.2.1 on 2019-06-02 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCare',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(default=False)),
                ('website', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(default=False)),
            ],
        ),
    ]
